create table
  public.products (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    products_name character varying null,
    products_price character varying null,
    product_description character varying null,
    products_note smallint null,
    constraint producrs_pkey primary key (id)
  ) tablespace pg_default;